---
- name: Download the kubens archive.
  get_url:
    url: "{{ kubens_download_url }}"
    dest: /tmp
    checksum: sha256:{{ kubens_checksum_url }}
    mode: 0755
  register: kubens_download

- name: Unarchive the kubens archive.
  unarchive:
    src: "{{ kubens_download.dest }}"
    dest: /tmp
    mode: 0755
    remote_src: true
  register: abc

- name: Copy the kubens binary into place.
  copy:
    src: /tmp/kubens
    dest: "{{ kubens_bin_path }}"
    mode: 0755
    remote_src: true
  become: true
